typedef enum
{
    DATABASE_ADD,
    DATABASE_UPDATE,
    DATABASE_DELETE,
    DATABASE_LIST,
    DATABASE_GET_LIST,
    DATABASE_LIST_FAVORITES,
    DATABASE_GET,
    DATABASE_PURGEALL,
} Database_operation_t;
